dist: trusty
sudo: false
language: python
python:
  - "2.7"

cache: pip

branches:
  only:
    - master

install:
  - pip install -r requirements.txt # for package.
  - pip install pylint # for lint test

script:
  - python -c "import tensorflow as tf;"
  - bash tests/run_tests.sh
